BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE NhanVien CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/ 

CREATE TABLE NhanVien(
    MaNV VARCHAR(4),
    HoTen VARCHAR2(20),
    NgaySinh DATE,
    DiaChi VARCHAR2(30),
    CMND VARCHAR2(20),
    ChucVu VARCHAR2(20),
    SDT VARCHAR2(10),
    CONSTRAINT PK_NhanVien PRIMARY KEY (MaNV) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE KhachHangTheoDoan CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE KhachHangTheoDoan(
    MaKH VARCHAR(4),
    MaDoan VARCHAR(4),
    Email VARCHAR2(20),
    SoFax VARCHAR2(20),
    SDT VARCHAR2(10),
    DiaChi VARCHAR2(30),
    CMND VARCHAR2(20),
    HoTen VARCHAR2(20),
    CONSTRAINT PK_KhachHangTheoDoan PRIMARY KEY (MaKH) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Doan CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE Doan(
    MaDoan VARCHAR(4),
    TenDoan VARCHAR2(20),
    MaNguoiDaiDien VARCHAR(4),
    SoLuong NUMBER,
    CONSTRAINT PK_Doan PRIMARY KEY (MaDoan) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE KhachHang CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE KhachHang(
    MaKH VARCHAR(4),
    HoTen VARCHAR2(20),
    Email VARCHAR2(20),
    SoFax VARCHAR2(20),
    SDT VARCHAR2(10),
    DiaChi VARCHAR2(30),
    CMND VARCHAR2(20),
    MaDoan VARCHAR(4),
    CONSTRAINT PK_KhachHang PRIMARY KEY (MaKH) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ThongTinDatPhong CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE ThongTinDatPhong(
    ID VARCHAR(4),
    MaKH VARCHAR(4),
    NgayDatPhong DATE,
    NgayNhanPhong DATE,
    NgayKetThuc DATE,
    HinhThucDatPhong VARCHAR2(20),
    SLgPhong NUMBER,
    SoDemLuuTru NUMBER,
    LoaiPhong VARCHAR2(20),
    HinhThucThanhToan VARCHAR2(20),
    YeuCauDacBiet VARCHAR2(20),
    CONSTRAINT PK_ThongTinDatPhong PRIMARY KEY (ID) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Phong CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE Phong(
    MaPhong VARCHAR(4),
    TinhTrangPhong VARCHAR2(20),
    DichVuHoTro VARCHAR2(20),
    LoaiPhong VARCHAR2(20),
    SoLuongPhong NUMBER,
    TrangThaiPhong VARCHAR2(20),
    Gia NUMBER,
    ChuongTrinhKhuyenMai VARCHAR2(20),
    CONSTRAINT PK_Phong PRIMARY KEY (MaPhong) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ThongTinVanChuyenHanhLy CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE ThongTinVanChuyenHanhLy(
    MaThongTinVanChuyen VARCHAR(4),
    MaPhong VARCHAR(4),
    MaKH VARCHAR(4),
    SoLuong NUMBER,
    NgayThang DATE,
    TinhTrang VARCHAR2(20),
    MaNV VARCHAR(4),
    CONSTRAINT PK_ThongTinVanChuyenHanhLy PRIMARY KEY (MaThongTinVanChuyen) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DaiLyTrungGian CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE DaiLyTrungGian(
    MaDaiLy VARCHAR(4),
    TenDaiLy VARCHAR2(20),
    SDT VARCHAR2(10),
    CONSTRAINT PK_DaiLyTrungGian PRIMARY KEY (MaDaiLy) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PhieuDangKyNhanPhong CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE PhieuDangKyNhanPhong(
    MaPhieuDKyNhanPhong VARCHAR(4),
    ID VARCHAR(4),
    MaKH VARCHAR(4),
    YeuCauDacBiet VARCHAR2(20),
    HoTen VARCHAR2(20),
    CMND VARCHAR2(20),
    CONSTRAINT PK_PhieuDangKyNhanPhong PRIMARY KEY (MaPhieuDKyNhanPhong) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DanhSachPhongDat CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE DanhSachPhongDat(
    ID VARCHAR(4),
    MaKH VARCHAR(4),
    MaPhong VARCHAR(4)
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PhieuDatPhong CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE PhieuDatPhong(
    MaPhieuDatPhong VARCHAR(4),
    ID VARCHAR(4),
    LoaiPhieu VARCHAR2(20),
    NgayNhanPhong DATE,
    NgayKetThuc DATE,
    SoDemLuuTru NUMBER,
    TongTien NUMBER,
    MaKH VARCHAR(4),
    MaNV VARCHAR(4),
    CONSTRAINT PK_PhieuDatPhong PRIMARY KEY (MaPhieuDatPhong) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HoaDonThanhToan CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE HoaDonThanhToan(
    MaHoaDon VARCHAR(4),
    MaKH VARCHAR(4),
    MaHoSo VARCHAR(4),
    Thue NUMBER,
    TongTien NUMBER,
    NgayThanhToan DATE,
    CONSTRAINT PK_HoaDonThanhToan PRIMARY KEY (MaHoaDon) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE HoSoThanhToan CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE HoSoThanhToan(
    MaHoSo VARCHAR(4),
    MaKH VARCHAR(4),
    MaDangKy VARCHAR(4),
    PhuongThuc VARCHAR2(20),
    TongTien NUMBER,
    NgayThanhToan DATE,
    SoTienConLai NUMBER,
    ThoiGian TIMESTAMP,
    MaNV VARCHAR(4),
    CONSTRAINT PK_HoSoThanhToan PRIMARY KEY (MaHoSo) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DanhSachThanhToan CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE DanhSachThanhToan(
    MaHoSo VARCHAR(4),
    Ten VARCHAR2(20),
    SoLuong NUMBER,
    Gia NUMBER,
    TongGia NUMBER
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DichVu CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE DichVu(
    MaDichVu VARCHAR(4),
    TenDV VARCHAR2(20),
    Gia NUMBER,
    CONSTRAINT PK_DichVu PRIMARY KEY (MaDichVu) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Tour CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE Tour(
    MaTour VARCHAR(4),
    ThoiGianKhoiHanh DATE,
    MaDonViLuHanh  VARCHAR(4),
    SoLuong NUMBER,
    LoaiDichVu VARCHAR2(20),
    NhuCauDacBiet VARCHAR2(20),
    Gia NUMBER,
    CONSTRAINT PK_Tour PRIMARY KEY (MaTour) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE SanPham CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE SanPham(
    MaSanPham VARCHAR(4),
    TenSP VARCHAR2(20),
    SoLuong NUMBER,
    GiaSanPham NUMBER,
    CONSTRAINT PK_SanPham PRIMARY KEY (MaSanPham) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE ThongTinDangKyDichVu CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE ThongTinDangKyDichVu(
    MaDangKy VARCHAR(4),
    MaKH VARCHAR(4),
    HoTroDichVu VARCHAR2(20),
    NgayDatLich DATE,
    MaDichVu VARCHAR(4),
    MaSanPham VARCHAR(4),
    MaTour VARCHAR(4),
    MaNV VARCHAR(4),
    CONSTRAINT PK_ThongTinDangKyDichVu PRIMARY KEY (MaDangKy) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DanhSachThamGiaTour CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE DanhSachThamGiaTour(
    MaTour VARCHAR(4),
    MaKH VARCHAR(4),
    STT NUMBER
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DonViLuHanh CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE DonViLuHanh(
    MaDonViLuHanh VARCHAR(4),
    TenDonViLuHanh VARCHAR2(20),
    SDT VARCHAR2(10),
    Email VARCHAR2(20),
    CONSTRAINT PK_DonViLuHanh PRIMARY KEY (MaDonViLuHanh) -- Tao khoa chinh
    );
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE DanhSachKhachHangChoDat CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
      RAISE; 
      END IF;
END;
/
CREATE TABLE DanhSachKhachHangChoDat(
    MaKH VARCHAR(4),
    NgayNhanPhong DATE,
    NgayKetThuc DATE
    );
/

--KHOA NGOAI

--KHOA NGOAI THONGTINDATPHONG
ALTER TABLE THONGTINDATPHONG
ADD CONSTRAINT FK_THONGTINDATPHONG_MAKH
FOREIGN KEY (MAKH)
REFERENCES KHACHHANG(MAKH)
ON DELETE CASCADE;

ALTER TABLE THONGTINDATPHONG
ADD CONSTRAINT FK_THONGTINDATPHONG_TTDL
FOREIGN KEY (HINHTHUCDATPHONG)
REFERENCES DAILYTRUNGGIAN(MADAILY)
ON DELETE CASCADE;

--KHOA NGOAI DOAN
ALTER TABLE DOAN
ADD CONSTRAINT FK_DOAN_KHACHHANG_MANGUOIDAIDIEN
FOREIGN KEY (MANGUOIDAIDIEN)
REFERENCES KHACHHANG(MAKH)
ON DELETE CASCADE;

--KHOA NGOAI KHACHANG
ALTER TABLE KHACHHANG
ADD CONSTRAINT FK_KHACHHANG_DOAN
FOREIGN KEY (MaDoan)
REFERENCES DOAN(MaDoan)
ON DELETE CASCADE;

--KHOA NGOAI THONGTINCHUYENHANHLY 
ALTER TABLE THONGTINVANCHUYENHANHLY
ADD CONSTRAINT FK_TTVCHL_KHACHHANG
FOREIGN KEY (MAKH)
REFERENCES KHACHHANG(MAKH)
ON DELETE CASCADE;

ALTER TABLE THONGTINVANCHUYENHANHLY
ADD CONSTRAINT FK_TTVCHL_PHONG
FOREIGN KEY (MAPHONG)
REFERENCES PHONG(MAPHONG)
ON DELETE CASCADE;

ALTER TABLE THONGTINVANCHUYENHANHLY
ADD CONSTRAINT FK_TTVCHL_NHANVIEN
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)
ON DELETE CASCADE;

--KHOA NGOAI PHIEUDANGKYPHONG
ALTER TABLE PhieuDangKyNhanPhong
ADD CONSTRAINT FK_PDKP_THONGTINDATPHONG
FOREIGN KEY (ID)
REFERENCES ThongTinDatPhong(ID)
ON DELETE CASCADE;

--KHOA NGOAI DANHSACHPHONGDAT
ALTER TABLE DANHSACHPHONGDAT
ADD CONSTRAINT FK_DSPD_THONGTINDATPHONG
FOREIGN KEY (ID)
REFERENCES THONGTINDATPHONG(ID)
ON DELETE CASCADE;

ALTER TABLE DANHSACHPHONGDAT
ADD CONSTRAINT FK_DSPD_PHONG
FOREIGN KEY (MAPHONG)
REFERENCES PHONG(MAPHONG)
ON DELETE CASCADE;

--KHOA NGOAI PHIEUDATPHONG
ALTER TABLE PHIEUDATPHONG
ADD CONSTRAINT FK_PDP_THONGTINDATPHONG
FOREIGN KEY (ID)
REFERENCES THONGTINDATPHONG(ID)
ON DELETE CASCADE;

ALTER TABLE PHIEUDATPHONG
ADD CONSTRAINT FK_DSPD_NHANVIEN
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)
ON DELETE CASCADE;

--KHOA NGOAI HOADOTHANHTOAN
ALTER TABLE HOADONTHANHTOAN
ADD CONSTRAINT FK_HDTT_HSTT
FOREIGN KEY (MAHOSO)
REFERENCES HOSOTHANHTOAN(MAHOSO)
ON DELETE CASCADE;

--KHOA NGOAI HOSOTHANHTOAN
ALTER TABLE HOSOTHANHTOAN
ADD CONSTRAINT FK_HSTT_NHANVIEN
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)
ON DELETE CASCADE;

--KHOA NGOAI DANHSACHTHANHTOAN
ALTER TABLE DANHSACHTHANHTOAN
ADD CONSTRAINT FK_DSTT_HSTT
FOREIGN KEY (MAHOSO)
REFERENCES HOSOTHANHTOAN(MAHOSO)
ON DELETE CASCADE;

--KHOA NGOAI TOUR
ALTER TABLE TOUR
ADD CONSTRAINT FK_TOUR_DONVILUHANH
FOREIGN KEY (MADONVILUHANH)
REFERENCES DONVILUHANH(MADONVILUHANH)
ON DELETE CASCADE;

--KHOA NGOAI THONGTINDANGKYDICHVU
ALTER TABLE THONGTINDANGKYDICHVU
ADD CONSTRAINT FK_THONGTINDANGKYDICHVU_DICHVU
FOREIGN KEY (MADICHVU)
REFERENCES DICHVU(MADICHVU)
ON DELETE CASCADE;

ALTER TABLE THONGTINDANGKYDICHVU
ADD CONSTRAINT FK_THONGTINDANGKYDICHVU_SANPHAM
FOREIGN KEY (MASANPHAM)
REFERENCES SANPHAM(MASANPHAM)
ON DELETE CASCADE;

ALTER TABLE THONGTINDANGKYDICHVU
ADD CONSTRAINT FK_THONGTINDANGKYDICHVU_TOUR
FOREIGN KEY (MATOUR)
REFERENCES TOUR(MATOUR)
ON DELETE CASCADE;


ALTER TABLE THONGTINDANGKYDICHVU
ADD CONSTRAINT FK_THONGTINDANGKYDICHVU_NHANVIEN
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)
ON DELETE CASCADE;

--KHOA NGOAI DANHSACHTHAMGIATOUR
ALTER TABLE DANHSACHTHAMGIATOUR
ADD CONSTRAINT FK_DANHSACHTHAMGIATOUR_TOUR
FOREIGN KEY (MATOUR)
REFERENCES TOUR(MATOUR)
ON DELETE CASCADE;


